---
- name: Install Wazuh Agent on TFS
  hosts: localhost
  gather_facts: no
  tasks: 
 #--------------------------------------------Deploy agent---------------------------------------------------------------------------

    - name: Download and install the agent
      shell: wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.12.0-1_amd64.deb && sudo WAZUH_MANAGER='192.168.159.32' dpkg -i ./wazuh-ag>
 
    - name: Recargar configuración de systemd
      shell: sudo systemctl daemon-reload

    - name: Habilitar el servicio wazuh-agent
      shell: sudo systemctl enable wazuh-agent

    - name: Iniciar el servicio wazuh-agent
      shell: sudo systemctl start wazuh-agent