apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: agent1
    namespace: default
  spec:
    containers:
    - image: javi14t/wazuh-agent-nmap:latest
      name: pod
      command: ["sh", "-c", "/var/ossec/bin/wazuh-control start && tail -f /var/ossec/logs/ossec.log"]
      securityContext:
        privileged: true
