apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      containers:
      - name: wazuh-agent
        image: javi14t/wazuh-agent-nmap:latest
        command: ["sh", "-c", "/var/ossec/bin/wazuh-control start && tail -f /var/ossec/logs/ossec.log"]
        securityContext:
          privileged: true