FROM ubuntu:20.04


ENV DEBIAN_FRONTEND=noninteractive

# Instalación de paquetes necesarios, limpieza de cache y archivos temporales
RUN apt-get update && \
    apt-get install -y python3 nano net-tools openssh-server sudo tcpdump iputils-ping curl iproute2 traceroute iperf3 gpg supervisor python3-pip nmap && \
    pip3 install python-nmap && \
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring /usr/share/keyrings/wazuh.gpg --import && \
    chmod 644 /usr/share/keyrings/wazuh.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list && \
    apt-get update && \
    WAZUH_MANAGER="192.168.159.32" apt-get install -y wazuh-agent && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


    
# Creamos el nuevo usuario con su contraseña y lanzamos el servicio ssh
RUN useradd -m -s /bin/bash -g root -G sudo -u 1000 cognet  && \
echo "cognet:supercognet" | chpasswd && \
#sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#echo 'root:root' | chpasswd && \
service ssh start

RUN  mkdir -p /home/cognet/logs/ && \
chown -R root:root /home/cognet/logs/ && \
chmod -R 777 /home/cognet/logs/

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /home/cognet

# Agrega configuración para supervisord
COPY supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY app/ /home/cognet/

COPY wazuh_conf/ossec.conf /var/ossec/etc/ossec.conf

# Inicia supervisord en primer plano para evitar cierre de contenedor
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

